# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=17)),
                ('publisher', models.CharField(max_length=128)),
                ('genre', models.IntegerField(choices=[(1, 'Romans'), (2, 'Obyczajowa'), (3, 'Sci-fi i fantasy'), (4, 'Literatura faktu'), (5, 'Popularnonaukowa'), (6, 'Poradnik'), (7, 'Kryminał'), (8, 'Klasyka'), (9, 'Historia'), (10, 'Poezja'), (11, 'Przygodowa'), (12, 'Bajki'), (13, 'Komiks'), (14, 'Dramat'), (15, 'Literatura współczesna')])),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
